### ISSUE TITLE
DM me on discord or comment below for the case you read this 

### ISSUE THREAD

**Issue by CoreTaxxe** [adamhb123/PygMov#3]
Hey there,
remember our old project?
I finished it a couple months ago though we lost contact somehow.
For the case you read this you may want to answer : P
my discord is _LegitSteve_#3842

**Comment by adamhb123** [comment]
Yeah I remember this! I saw you put out the release. I tried adding you on Discord but it didn't work. I just moved into college so I won't be able to work on the project or anything but I wouldn't mind chatting a little.

**Comment by adamhb123** [comment]
If you want to add me: Hackerman#0121
